"""
Script to filter JSONL files based on prompt and/or response length.
Useful for filtering training data generated by OpenRouter API calls.
"""

import json
import argparse
from typing import Optional


def filter_jsonl_by_length(
    input_path: str,
    output_path: str,
    min_prompt_length: Optional[int] = None,
    max_prompt_length: Optional[int] = None,
    min_response_length: Optional[int] = None,
    max_response_length: Optional[int] = None,
    prompt_field: str = "prompt",
    response_field: str = "response",
):
    """
    Filter JSONL file based on prompt and/or response length.

    Args:
        input_path: Path to input JSONL file
        output_path: Path to output filtered JSONL file
        min_prompt_length: Minimum prompt length (characters)
        max_prompt_length: Maximum prompt length (characters)
        min_response_length: Minimum response length (characters)
        max_response_length: Maximum response length (characters)
        prompt_field: Name of the field containing prompts
        response_field: Name of the field containing responses
    """
    filtered_count = 0
    total_count = 0

    with open(input_path, "r") as infile, open(output_path, "w") as outfile:
        for line in infile:
            total_count += 1
            item = json.loads(line.strip())

            # Get prompt and response
            prompt = item.get(prompt_field, "")
            response = item.get(response_field, "")

            # Check prompt length constraints
            if min_prompt_length is not None and len(prompt) < min_prompt_length:
                continue
            if max_prompt_length is not None and len(prompt) > max_prompt_length:
                continue

            # Check response length constraints
            if min_response_length is not None and len(response) < min_response_length:
                continue
            if max_response_length is not None and len(response) > max_response_length:
                continue

            # Write filtered item
            outfile.write(json.dumps(item) + "\n")
            filtered_count += 1

    print(
        f"Filtered {filtered_count}/{total_count} items ({filtered_count / total_count * 100:.1f}%)"
    )
    print(f"Output written to: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Filter JSONL files based on prompt and/or response length"
    )
    parser.add_argument("input_path", type=str, help="Path to input JSONL file")
    parser.add_argument(
        "output_path", type=str, help="Path to output filtered JSONL file"
    )
    parser.add_argument(
        "--min-prompt-length",
        type=int,
        default=None,
        help="Minimum prompt length in characters",
    )
    parser.add_argument(
        "--max-prompt-length",
        type=int,
        default=None,
        help="Maximum prompt length in characters",
    )
    parser.add_argument(
        "--min-response-length",
        type=int,
        default=None,
        help="Minimum response length in characters",
    )
    parser.add_argument(
        "--max-response-length",
        type=int,
        default=None,
        help="Maximum response length in characters",
    )
    parser.add_argument(
        "--prompt-field",
        type=str,
        default="prompt",
        help="Name of the field containing prompts (default: 'prompt')",
    )
    parser.add_argument(
        "--response-field",
        type=str,
        default="response",
        help="Name of the field containing responses (default: 'output')",
    )

    args = parser.parse_args()

    filter_jsonl_by_length(
        input_path=args.input_path,
        output_path=args.output_path,
        min_prompt_length=args.min_prompt_length,
        max_prompt_length=args.max_prompt_length,
        min_response_length=args.min_response_length,
        max_response_length=args.max_response_length,
        prompt_field=args.prompt_field,
        response_field=args.response_field,
    )


if __name__ == "__main__":
    main()
